on:
  [
    push,
    pull_request,
    pull_request_review,
    pull_request_review_comment,
    issues,
    issue_comment,
  ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: FraserTooth/go-to-sleep-action@test
        with:
          who-to-greet: "Mona the Octocat"
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
