on:
  [
    push,
    pull_request,
    pull_request_review,
    pull_request_review_comment,
    issues,
    issue_comment,
  ]

jobs:
  go_to_sleep_job:
    runs-on: ubuntu-latest
    name: Go To Sleep-o-tron
    steps:
      - name: GTFTSleep
        id: hello
        uses: FraserTooth/go-to-sleep-action@master
        with:
          custom_message: "GTFT Sleep!"
